//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MallDataBase.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Directory
    {
        public System.Guid ID { get; set; }
        public string DirectoryName { get; set; }
        public int Rank { get; set; }
        public Nullable<System.Guid> ParentDirectoryGuid { get; set; }
        public Nullable<int> SortNumber { get; set; }
        public string RelativeUrl { get; set; }
    }
}
